### ISSUE TITLE
problem with activation 

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa-contact-form-7#5]
I couldn't get this plugin to work. After some time I found that it works only with first activation. 

If you deactivate it, then you need to resave WpCasa options to rid contact_form_7_listing_form_id from options.  

php 7.0  WP 4.9.5  CF 7 5.0.1

Maybe this helps somebody.

**Comment by igorchernenko92** [comment]
Hi
Sorry for late replay, now we start to work on all wpcasa issues and enhance functionality 
Unfortunately i can't replicate this issue, evrth works perfectly
If someone has the same issue we will reopen this ticket
Thanks
