### ISSUE TITLE
Re-structure repo

### ISSUE THREAD

**Issue by JoeHana** [wpsight/wpcasa-contact-form-7#8]
In preparation for the automatic deployment we need to do the following things:
* [wp-assets](https://github.com/wpsight/wpcasa-contact-form-7/tree/master/wp-assets) needs to get moved into a separate branch [assets](https://github.com/wpsight/wpcasa-contact-form-7/tree/assets)
* the content of the [wpcasa-contact-form-7](https://github.com/wpsight/wpcasa-contact-form-7/tree/master/wpcasa-contact-form-7) plugin should get moved to the root of the master branch (where the readme.md is right now)

**Comment by igorchernenko92** [comment]
Done
